version: "3.3"
services:
  api:
    build: .
    image: $API_IMAGE
    container_name: confapi
    volumes:
      - ${LOG_DIR}:${LOG_DIR}
    ports:
      - ${API_PORT}:80
  database:
    image: "mysql:latest"
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1